---

- name: Include rootserver setup task
  ansible.builtin.include_tasks:
    file: rootserver_setup.yml

#- name: Include Proxmox installation task for bookworm
#  ansible.builtin.include_tasks:
#    file: bookworm_proxmox_install.yml
#  when: ansible_facts['distribution_release'] == "bookworm"

#- name: Include UFW installation task for bookworm
#  ansible.builtin.include_tasks:
#    file: bookworm_ufw.yml
#  when: ansible_facts['distribution_release'] == "bookworm"

...
